// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmNgApsyQge_fUA6Iyj8O3nHUzLKYIYNk',
    appId: '1:827181165046:android:6391028cae8f434ad57fd7',
    messagingSenderId: '827181165046',
    projectId: 'pet-app-487d5',
    databaseURL: 'https://pet-app-487d5-default-rtdb.firebaseio.com',
    storageBucket: 'pet-app-487d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArZMLg_s0RmnrRPYEU-D49T_G_Urx5c9I',
    appId: '1:827181165046:ios:8f4cd5ef6b3279bad57fd7',
    messagingSenderId: '827181165046',
    projectId: 'pet-app-487d5',
    databaseURL: 'https://pet-app-487d5-default-rtdb.firebaseio.com',
    storageBucket: 'pet-app-487d5.appspot.com',
    iosClientId: '827181165046-it41od84hnb97p1tu9arbupgi6f1476n.apps.googleusercontent.com',
    iosBundleId: 'com.example.petApp',
  );
}
